# -*- coding: utf-8 -*-
"""ABI Break Even Calculator - somaCtrl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A385AYRCe3cypgF2kckHbGTZB-UD5KLE
"""

def break_even_from_stats():
    """
    Uses ONLY the stats shown on the Arena Breakout Infinite profile page:
      - Total Raids
      - Extraction Rate (%)
      - Total Earned (in millions)

    Prints:
      - Win rate
      - Average profit on a winning raid
      - Break-even average loss per death
      - Break-even risk:reward ratio
    """

    # --- Inputs exactly as shown in the game UI ---
    total_raids = float(input("Total Raids (e.g. 1900): "))
    extraction_rate_percent = float(input("Extraction Rate % (e.g. 35.5): "))
    total_earned_millions = float(input("Total Earned in millions (e.g. 704.3): "))

    # --- Convert to useful values ---
    p = extraction_rate_percent / 100.0          # win rate as decimal
    total_earned = total_earned_millions * 1_000_000  # koen
    wins = total_raids * p

    if wins <= 0 or p <= 0 or p >= 1:
        raise ValueError("Check your stats: extraction rate must be between 0 and 100 and wins > 0.")

    # Average profit on a winning raid
    avg_win = total_earned / wins

    # Break-even average loss per losing raid (negative number)
    # L_BE = -(p * W) / (1 - p)
    L_BE = -(p * avg_win) / (1 - p)

    # Break-even Risk:Reward ratio
    # RR_BE = (1 - p) / p
    RR_BE = (1 - p) / p

    # --- Output ---
    print("\n=== Break-even Stats ===")
    print(f"Win rate: {p*100:.2f}%")
    print(f"Average winning raid profit: {avg_win:,.0f} koen ({avg_win/1_000_000:.3f} M)")

    print(f"\nBreak-even average loss per death: {L_BE:,.0f} koen ({L_BE/1_000_000:.3f} M)")
    print("  -> If your REAL average loss is smaller than this (in magnitude), you're profitable.")
    print("  -> If it's larger, you're losing over time.")

    print(f"\nBreak-even Risk:Reward ratio: {RR_BE:.2f} : 1")


if __name__ == "__main__":
    break_even_from_stats()